import random
numbers = [random.randint(1, 100) for _ in range(20)]
print(f"原始列表：{numbers}\n")
print("===== 筛选操作 =====")
osls = list(filter(lambda x: x % 2 == 0, numbers))
print(f"偶数：{osls}")
big50 = list(filter(lambda x: x > 50, numbers))
print(f"大于50的数：{big50}")
k3 = list(filter(lambda x: x % 3 == 0, numbers))
print(f"能被3整除的数：{k3}\n")
print("===== 转换操作 =====")
strs = list(map(lambda x: str(x), numbers))
print(f"转为字符串：{strs}")
nn = list(map(lambda x: x ** 2, numbers))
print(f"平方：{nn}")
bq = list(map(lambda x: "偶数" if x % 2 == 0 else "奇数", numbers))
print(f"奇偶标签：{bq}\n")
print("===== 排序操作 =====")
ge = sorted(numbers, key=lambda x: x % 10)
print(f"按个位数排序：{ge}")
sh = sorted(numbers, key=lambda x: (x // 10) % 10)
print(f"按十位数排序：{sh}")